services:

  app:
    build: .
    container_name: app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "3000:3000"
    restart: always

  mongo:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: